# Site settings
description: "Homepage of Chamoy: Hacker Freelance and Algorithm Maniac "
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:3000/"

# User settings
username: chamoysvoice
user_description: a sushi hungry hacker
user_title: Web Developer
email: chamoysvoice@gmail.com
twitter_username: chamoysvoice
github_username:  chamoysvoice
gplus_username:  Chamoy Donnie
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
#exclude: ['package.json', 'src', 'node_modules']
